### PR TITLE
Add OpenGraph data

### PR DESCRIPTION
**Pull request by MineRobber9000**
This allows for rich embeds. As this is primarily a backend change, nothing should truly change in the articles department (merge conflicts should be easily fixed).

 - [X] Add OGP generation to `templates/article.html`
    * [X] Add configuration to change the absolute path of the published neowiki build
    * [X] Get an image to use
 - [X] Fix any OGP generation problems we have regarding the main page (`templates/mainpage.html`)
    * [X] Add override section to OGP tags
    * [X] Figure out OGP values for main page

(Don't mind the first commit, forgot I wasn't in master.)

### CODE REVIEW

**Comment by MineRobber9000** [comment]
The only required change now is to get an image to use for the wiki embeds. Anyone have any ideas how to get one? Should we bug Capy?

**Comment by dotcomboom** [comment]
Dropping these here for future reference. Globe graphic shamelessly lifted from [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Globe_Atlantic.svg) (public domain).
image

image

and this is le fancy one!
image

**Comment by MineRobber9000** [comment]
The logo is the blocking change. When I get home I'll add the logo (I think I'll go with le fancy one) and then this can be merged. The other PRs can then be merged.

(also, I can use the non-fancy one on the button design (it's able to be represented in a small space))

**Comment by MineRobber9000** [comment]
I'm going to merge this now that it's done.

**Pull request merged**
