### PR TITLE
Make page on Districts

### PR DESCRIPTION
**Pull request by MineRobber9000**
(re: https://trello.com/c/ghqjGu92/3-districts)

Parts:

 - [x] Intro
 - [x] History (and Seb?)
 - [x] Staff
     - [x] Sebastian - minerobber
     - [x] mariteaux - minerobber
     - [x] lempamo - elementz
     - [x] dotcomboom - elementz
     - [x] Capy - MIA
     - [x] Cheren - MIA
 - [x] Cover the districts
     - [x] Arcadia - elementz
     - [x] Silicon Valley - elementz
     - [x] Tokyo - elementz
     - [x] Arles - MineRobber
     - [x] Stratford-upon-Avon - MineRobber
     - [x] Silver Lake - MineRobber
     - [x] Petsburg - MIA
     - [x] Purgatory - MIA
     - [x] Oxford - elementz
     - [x] Hollywood - elementz
 - [x] (former) Discord server

### CODE REVIEW

**Comment by MineRobber9000** [comment]
Arles:

Arles is a district for "drawings, photos, [and] visual art". It features artists such as [Capy](https://gwtagacw.neocities.org/), [ily](https://ily.neocities.org/), as well as [MIA (aka punchy)](https://punchy.neocities.org/). To be included in this district, you must either be an artist or have a page that is a work of art itself.

(what do you guys think?)

**Comment by jsaji06** [comment]
Yes, pretty good article.

**Comment by jsaji06** [comment]
Arcadia:

[Arcadia](https://districts.neocities.org) is a district for "video games, puzzles, [and] toys".  It contains sites like  [2-Bit](https://2bit.neocities.org/), [lancer502](https://lancer502.neocities.org), and [mariteaux](https://mariteaux.neocities.org). To be included in this district, you must have a site that has at least a decent portion of it dedicated to toys, games, or puzzles.

**Comment by MineRobber9000** [comment]
Stratford-upon-Avon:

[Stratford-upon-Avon](https://districts.neocities.org/stratford-upon-avon/) is a district for "writing, and the writers who write it". Named after Shakespeare's hometown, it is home to such sites as [Rainstorms in July](https://rainstormsinjuly.co/), [The International OwlTech Initiative](https://owltech.neocities.org/), and [these caverns called home](https://cavernscalledhome.neocities.org/). To be included in this district, you must write things and/or have a site dedicated to writing.

**Comment by MineRobber9000** [comment]
Just so we have a standard format for them (so it doesn't look like 3 totally different people wrote the listings, even though that is the case), please use a format similar to this:

[DISTRICT](# "link the district here") is a district for "(quote/add to a quote of the description on the page)". (fact, if there is one), it (features/hosts/contains) (list 3 sites). To be included in this district, you must (what you need to do).

So, for example, rewriting your Arcadia example @elementzprojects:

[Arcadia](https://districts.neocities.org/arcadia/) is a district for "video games, puzzles, [and] toys". It contains sites like [2-Bit](https://2bit.neocities.org/), [lancer502](https://lancer502.neocities.org/), and [mariteaux](https://mariteaux.neocities.org/). To be included in this district, you must have a site that has at least a decent portion of it dedicated to toys, games, or puzzles.

**Comment by jsaji06** [comment]
Silicon Valley:

[Silicon Valley](https://districts.neocities.org/silicon-valley) is a district for "hardware, software, [and] programming". Named after a region located in California, known for technological advances, it features sites such as [elementz](https://elementz.neocities.org), [dotcomboom](https://dotcomboom.neocities.org), and [joppiesaus](https://joppiesaus.neocities.org). To be included in this district, you must have hardware, programming, or software-related content.

**Comment by jsaji06** [comment]
Tokyo:

[Tokyo](https://districts.neocities.org/tokyo) is a district for "anime, manga, Asian pop, [and] the far east". Named after the capital of Japan, it features sites such as [anipike](https://anipike.neocities.org), [ily](https://ily.neocities.org), and [fauux](https://fauux.neocities.org). To be included in this district, you must have a decent portion of anime, manga, asian pop, or the far east-related content.

**Comment by MineRobber9000** [comment]
> To be included in silicon valley

Replace "silicon valley" with "this district" and give me the markdown source and I'll toss it in.

**Comment by MineRobber9000** [comment]
Purgatory:
```
[Purgatory](https://districts.neocities.org/purgatory/) is a district for "????????????????????". The Purgatory is a state after death where the souls of sinner get ‘purified’ in order to reach heaven. It contains sites like [Big Gulp Supreme](https://biggulpsupreme.neocities.org/),[Jackomix](https://jackomix.neocities.org/), and [max2019](https://max2019.neocities.org/). To be included in this district, you must not have enough content or enough focus to fit into any other District.
```
[Purgatory](https://districts.neocities.org/purgatory/) is a district for "????????????????????". The Purgatory is a state after death where the souls of sinner get ‘purified’ in order to reach heaven. It contains sites like [Big Gulp Supreme](https://biggulpsupreme.neocities.org/),[Jackomix](https://jackomix.neocities.org/), and [max2019](https://max2019.neocities.org/). To be included in this district, you must not have enough content or enough focus to fit into any other District.

Petsburg:
```
[Petsburg](https://districts.neocities.org/petsburg/) is a district for "animals and the people who love them". it features sites such as [GwtaGacw](https://gwtagacw.neocities.org/), [Bugland](https://bugland.neocities.org/), and   [Tinypaws](https://tinypaws.neocities.org/). To be included in this district, your site must have a central focus on pets or wild animals.
```
[Petsburg](https://districts.neocities.org/petsburg/) is a district for "animals and the people who love them". it features sites such as [GwtaGacw](https://gwtagacw.neocities.org/), [Bugland](https://bugland.neocities.org/), and   [Tinypaws](https://tinypaws.neocities.org/). To be included in this district, your site must have a central focus on pets or wild animals.

**Comment by MineRobber9000** [comment]
Silver Lake:

[Silver Lake](https://districts.neocities.org/silver-lake/) is a district for "Music and things with melodies". It contains such sites as [mariteaux](https://mariteaux.neocities.org/), [strata](https://strata.neocities.org/), and [hosma](hosma.neocities.org). To be included in this district, you must have a focus on music in your site's content.

**Comment by MineRobber9000** [comment]
For whoever writes the staff section:

 - Lempamo is a staff member from beginning to 2018-11-04. (Left due to ideological differences)
 - dotcomboom is a staff member from 2018-11-04 and on.
 - Anyone in the [Staff section here](https://districts.neocities.org/about/) is a staff member from beginning to end.

**Comment by jsaji06** [comment]
Oxford:

Oxford is a district for "information, and education".Named after the university located in Oxford, England, it contains sites such as [Edlinfan](https://edlinfan.neocities.org), [Days of Pride](https://daysofpride.neocities.org), and [I Hate Carpet](https://ihatecarpet.neocities.org). To be included in this district, you must have a decent portion of education or information-related content.

**Comment by jsaji06** [comment]
Hollywood:

Hollywood is a district for "cartoons, movies, [and] western media". Named after the neighborhood and tourist attraction located in Los Angeles, California, it contains sites such as [Do You Remember Fun House?](https://doyourememberfunhouse.neocities.org), [Telescuff](https://telescuff.neocities.org), and [Up All Night](https://upallnight.neocities.org). To be included in this district, you must have a decent portion of films or TV show-related content.

**Comment by jsaji06** [comment]
**FOLLOWING POSTS AFTER THIS ARE ABOUT STAFF MEMBERS OF DISTRICTS**

**Staff**
Sebastian

blah blah

mariteaux

blah blah

dotcomboom

blah blah

Capy

blah blah

cheren (bugland)

blah blah 

(...thoughts?)

**Comment by MineRobber9000** [comment]
(it should probably be in a longform paragraph, but the sections can be written independently.)

mariteaux:

[mariteaux](https://mariteaux.neocities.org/) is the passionate project lead of Neocities Districts, "coordinating efforts and working with the site markup" ([Districts about page](https://districts.neocities.org/about/)). His site is in the [Arcadia](https://districts.neocities.org/arcadia/) and [Silver Lake](https://districts.neocities.org/silver-lake/) districts.

**Comment by MineRobber9000** [comment]
Their Discord server has been canned.

**Comment by MineRobber9000** [comment]
So I've assigned the staff members equally split. (I'm as good a person as any to write about mari :P)

**Comment by MineRobber9000** [comment]
Sebastian:

```
Sebastian (shortened to Seb) - The Districts mascot, tasked with "[sorting all of the sites on Districts](https://districts.neocities.org/about/)". He is canonically [a blue-and-yellow armadillo with black square glasses](https://districts.neocities.org/images/staff/seb.png). [An entire section of the Districts site is dedicated to Seb fanart.](https://districts.neocities.org/fanart/)
```

Sebastian (shortened to Seb) - The Districts mascot, tasked with "[sorting all of the sites on Districts](https://districts.neocities.org/about/)". He is canonically [a blue-and-yellow armadillo with black square glasses](https://districts.neocities.org/images/staff/seb.png). [An entire section of the Districts site is dedicated to Seb fanart.](https://districts.neocities.org/fanart/)

**Comment by jsaji06** [comment]
dotcomboom:

dotcomboom is the site manager of districts. The districts website uses his software, AutoSite, which "helps you keep all of your website's pages in the same basic template" ([dotcomboom](https://dotcomboom.neocities.org/software/autosite.html), 1). His site is in the [Silicon Valley](https://districts.neocities.org/silicon-valley/) district.

**Comment by jsaji06** [comment]
So, 83% of the staff members decided to leave Neocities to Somnolescent. For the final draft, we need to make everything past tense.

**Comment by jsaji06** [comment]
lempamo:

lempamo was the miscellaneous and backup programmer of districts. He left and was kicked out of districts, and the discord server respectively due to ideological differences.

**Comment by jsaji06** [comment]
The Neocities Districts is a site directory for Neocities, which is broken down to 6 categories to make site searching much more simpler, regarding your interests. The URL was originally owned by dotcomboom, and the very first version of Districts was for Geocities neighborhoods, which was unsuccessful. When Hyperlink 1.0 died, Districts then was envisioned as moden-day DMOZ, and for this version, there was a prototype. This was also unsuccessful. Finally, lempamo decided to help with Districts around August of 2018, and that was when Districts went live and got successful. Capy, Cheren, and later dotcomboom decided to help out as well. Around October 2018 was the time Districts became public.

**Comment by MineRobber9000** [comment]
Alright, I think this is good.

**Comment by MineRobber9000** [comment]
Now that we've finished, this can finally be merged.

**Pull request merged**
